baseURL = 'https://blog.eeswepe.my.id/'  # Ganti dengan URL blog kamu
languageCode = 'en-us'
title = 'EESWEBLOG'
theme = 'PaperMod'

# pagination
[pagination]
  pagerSize = 5

# menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 3

# taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# params
[params]

  comments = true

  ShowPostTags = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "Hi there wave"
    Content = "Can be Info, links, about..."

  [[params.socialIcons]]
    name = "Github"
    url = "<link>"

  [[params.socialIcons]]
    name = "Instagram"
    url = "<link2>"

